---@class LuaSettings
local SS = settings.startup

if SS["bobmods-enemies-enableartifacts"] then
	if mods["bobenemies"] and mods["reskins-bobs"] and mods["SaltedFish"] and mods["Power-Armour-Replacer"] then
		data:extend({
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactRed",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-red.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZA",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-red", amount=20}},
			},
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactOrange",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-orange.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZB",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-red", amount=20}},
			},
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactYellow",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-yellow.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZC",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-yellow", amount=20}},
			},
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactGreen",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-green.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZD",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-green", amount=20}},
			},
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactBlue",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-blue.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZE",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-blue", amount=20}},
			},
			{
				type = "recipe",
				category = "chemistry-or-cryogenics",
				name = "ArtifactPurple",
				icon = "__reskins-bobs__/graphics/icons/enemies/artifacts/bob-alien-artifact-purple.png",
				enabled = false,
				subgroup = "bob-alien-artifact",
				order = "ZF",
				allow_productivity = true,
				allow_decomposition = true,
				energy_required = 10.0,
				ingredients = {
					{type="fluid", name="bob-alien-artifact", amount=20},
					{type="item", name="sulfur", amount=25},
					{type="item", name="salt", amount=25},
					{type="item", name="carbon", amount=25},
				},
				results = {{type="item", name="bob-alien-artifact-purple", amount=20}},
			},
		})
	end
end