	require("prototypes.salted_fish.recipes")
	require("prototypes.salted_fish.tech")
	require("prototypes.woodgasification.Recipes")
	require("prototypes.woodgasification.Techs")
	require("mods.duplicate-items-data")