require("prototypes.bobs.recipe")
require("prototypes.bobs.RocketSilo")
require("prototypes.bobs.technology")
require("prototypes.SpaceBobsMinerals.Scraping")
require("prototypes.SpaceBobsMinerals.SpaceResorces")
require("prototypes.SpaceBobsMinerals.ResorceTech")
require("prototypes.vanilla-loaders.recipes")
require("prototypes.SpidertronExtended.misc")