require("Settings.ChemicalProcesssing")
require("Settings.VanillaLoaders")
require("Settings.SpaceAge")
require("Settings.AstroidCrushing")
require("Settings.WaterWell")
require("Settings.Recycling")
require("Settings.BigBags")